Repository bbta3-bppt/website, pull requests merged in 2021-04, with the labels that each got.

#77 Penyesuaian template dengan bootstrap 5 beta serta aset
  themes/bbta3/layouts/partials/breadcrumb.html
  themes/bbta3/layouts/partials/footer.html
  themes/bbta3/layouts/partials/head.html
  themes/bbta3/layouts/partials/header.html
  themes/bbta3/static/images/lapor/NoGratifikasi.svg
Labels: maintenance

#78 Update deploy workflow
  .github/workflows/deploy.yaml
Labels: dependencies

#80 Coba alternative set env
  .github/workflows/deploy.yaml
Labels: dependencies

#81 Kelola workflow untuk deploy dan harian
  .github/workflows/daily.yaml
  .github/workflows/deploy.yaml
Labels: dependencies

#82 Deteksi current user
  .github/workflows/deploy.yaml
Labels: dependencies

#83 Ganti versi website-worker
  .github/workflows/daily.yaml
  .github/workflows/deploy.yaml
Labels: dependencies

#84 Menambahkan pendekatan env di level CI
  .github/workflows/deploy.yaml
Labels: dependencies

#85 Melakukan pendekatan dengan ::set-env
  .github/workflows/deploy.yaml
Labels: dependencies

#86 Uji coba terapan source profile
  .github/workflows/deploy.yaml
Labels: dependencies

#87 Koreksi env workflow harian melalui source
  .github/workflows/daily.yaml
Labels: dependencies

#88 Update informasi headline BBTA3
  content/_index.md
Labels: documentation

#89 Koreksi button full width untuk bootstrap 5
  themes/bbta3/layouts/partials/banner.html
Labels: maintenance
